version: '3.9'

services:
  application:
    build:
      context: .
      target: run
    ports:
      - "5000:5000"
      - "5001:5001"
      - "6000:6000"
      - "6001:6001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DepuChef=Server=database;Database=myApp;User=sa;Password=MyPassword1;TrustServerCertificate=True
    depends_on:
      database:
          condition: service_started
      run_database_migrations:
        condition: service_completed_successfully
    profiles:
      - app

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPassword1
      - MSSQL_PID=Express
    expose:
      - "1433"
    profiles:
      - database

  run_database_migrations:
    build:
      context: .
      target: build
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      dotnet ef database update -p ../DepuChef.Infrastructure/DepuChef.Infrastructure.csproj -s DepuChef.Api.csproj --verbose
      "
    depends_on:
      - database
    profiles:
      - database
