version: '3.9'

services:
  application:
    build:
      context: . # Builds the app using the Dockerfile in the current directory
      target: run
    ports:
      - "8080:8080" # Maps port 8080 on the host to port 8080 in the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyAppDb;User=sa;Password=MyPassword1
    depends_on:
      - database # Ensures the app starts only after the database is up
    profiles:
      - app

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_db
    ports:
      - "1433:1433" # Maps SQL Server port 1433 on the host to port 1433 in the container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPassword1 # Replace with a strong password
      - MSSQL_PID=Developer # Developer edition of SQL Server
    volumes:
      - sql_data:/var/opt/mssql # Persists database files
    profiles:
      - database

  run_database_migrations:
    build:
      context: .
      target: build
    command: dotnet ef database update -p DepuChef.Infrastructure/DepuChef.Infrastructure.csproj -s DepuChef.Api/DepuChef.Api.csproj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=MyAppDb;User=sa;Password=MyPassword1
    depends_on:
      - database
    profiles:
      - database

volumes:
  sql_data:
