version: '3.9'

services:
  application:
    build:
      context: .
      target: run
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyAppDb;User=sa;Password=MyPassword1
    depends_on:
      - database
    profiles:
      - app

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPassword1
      - MSSQL_PID=Developer # Developer edition of SQL Server
    volumes:
      - sql_data:/var/opt/mssql # Persists database files
    profiles:
      - database

  run_database_migrations:
    build:
      context: .
      target: build
    command: dotnet ef database update -p DepuChef.Infrastructure/DepuChef.Infrastructure.csproj -s DepuChef.Api/DepuChef.Api.csproj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=MyAppDb;User=sa;Password=MyPassword1
    depends_on:
      - database
    profiles:
      - database

volumes:
  sql_data:
