name: Deploy .NET Web API to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    strategy:
      matrix:
        environment:
          - development          
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # # Run tests
    # - name: Run tests
    #   run: dotnet test --no-build --verbosity normal
    
    - name: Publish the project
      # if: success()  # Only run if previous steps were successful
      run: dotnet publish DepuChef.Api/DepuChef.Api.csproj -c Release -o publish_output --no-build
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE  }}
        package: publish_output