name: Deploy .NET Web API to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # # Run tests
    # - name: Run tests
    #   run: dotnet test --no-build --verbosity normal
    
    - name: Publish the project
      if: success()
      run: dotnet publish DepuChef.Api/DepuChef.Api.csproj -c Release -o publish_output --no-build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: depuchef-api
        path: publish_output
          
  deploy:
    strategy:
      matrix:
        environment:
          - development   
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: ${{ matrix.environment }} 
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: depuchef-api

    - name: Update database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -c DepuChefDbContext -p DepuChef.Api/DepuChef.Infrastructure -s DepuChef.Api/DepuChef.Api
    
    - name: Deploy to Azure Web Apps
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE  }}
        package: .