name: Deploy .NET Web API to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Restore, Build, and Publish
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish DepuChef.Api/DepuChef.Api.csproj -c Release -o publish_output

    - name: Bundle EF migrations
      run: |
        dotnet tool install --global dotnet-ef
        cd DepuChef.Infrastructure
        dotnet ef migrations bundle
        mv efbundle ../publish_output/efbundle.exe
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: depuchef-api
        path: publish_output

  deploy:
    needs: build-and-publish
    strategy:
      matrix:
        environment:
          - development
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: depuchef-api

    - name: Update Database
      run: |
        efbundle.exe --connection '${{ secrets.CONNECTION_STRING_DEPUCHEF }}'

    - name: Deploy to Azure Web Apps
      if: success()
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
        package: publish_output
